image: node:12.16.3

pages:
  cache:
    paths:
    - node_modules/

  script:
  - mkdir public
  - cd docs
  - yarn install
  - yarn docs:build
  artifacts:
    paths:
    - public
  only:
  - master