name: Deploy ipychart's documentation
on: 
  push:
    branches:
      - master    
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: vuepress-deploy
      uses: jenkey2011/vuepress-deploy@master
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        TARGET_REPO: nicohlr/ipychart
        TARGET_BRANCH: gh-pages
        BUILD_SCRIPT: cd docs && yarn install && yarn docs:build
        BUILD_DIR: ../public/